# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-19 16:18
from __future__ import unicode_literals

import ckeditor.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Title', models.CharField(max_length=50)),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Text', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
